version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=haris
      - MONGO_PASSWORD=haris_555
    command: npm run dev

  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: haris
      MONGO_INITDB_ROOT_PASSWORD: haris_555
